Molecule.destroy_all
Element.destroy_all

Molecule.create(atom1: "H", atom2: "H", energy: 436, bonds: 1)
Molecule.create(atom1: "H", atom2: "C", energy: 410, bonds: 1)
Molecule.create(atom1: "H", atom2: "F", energy: 570, bonds: 1)
Molecule.create(atom1: "H", atom2: "Cl", energy: 432, bonds: 1)
Molecule.create(atom1: "H", atom2: "Br", energy: 366, bonds: 1)
Molecule.create(atom1: "H", atom2: "I", energy: 298, bonds: 1)
Molecule.create(atom1: "H", atom2: "N", energy: 390, bonds: 1)
Molecule.create(atom1: "H", atom2: "O", energy: 460, bonds: 1)
Molecule.create(atom1: "H", atom2: "S", energy: 340, bonds: 1)

Molecule.create(atom1: "C", atom2: "H", energy: 410, bonds: 1)
Molecule.create(atom1: "C", atom2: "C", energy: 350, bonds: 1)
Molecule.create(atom1: "C", atom2: "F", energy: 450, bonds: 1)
Molecule.create(atom1: "C", atom2: "Cl", energy: 330, bonds: 1)
Molecule.create(atom1: "C", atom2: "Br", energy: 270, bonds: 1)
Molecule.create(atom1: "C", atom2: "I", energy: 240, bonds: 1)
Molecule.create(atom1: "C", atom2: "N", energy: 300, bonds: 1)
Molecule.create(atom1: "C", atom2: "O", energy: 350, bonds: 1)
Molecule.create(atom1: "C", atom2: "S", energy: 260, bonds: 1)

Molecule.create(atom1: "N", atom2: "H", energy: 390, bonds: 1)
Molecule.create(atom1: "N", atom2: "C", energy: 300, bonds: 1)
Molecule.create(atom1: "N", atom2: "F", energy: 270, bonds: 1)
Molecule.create(atom1: "N", atom2: "Cl", energy: 200, bonds: 1)
Molecule.create(atom1: "N", atom2: "Br", energy: 240, bonds: 1)
Molecule.create(atom1: "N", atom2: "I", energy: nil, bonds: 1)
Molecule.create(atom1: "N", atom2: "N", energy: 240, bonds: 1)
Molecule.create(atom1: "N", atom2: "O", energy: 200, bonds: 1)
Molecule.create(atom1: "N", atom2: "S", energy: nil, bonds: 1)

Molecule.create(atom1: "O", atom2: "H", energy: 460, bonds: 1)
Molecule.create(atom1: "O", atom2: "C", energy: 350, bonds: 1)
Molecule.create(atom1: "O", atom2: "F", energy: 180, bonds: 1)
Molecule.create(atom1: "O", atom2: "Cl", energy: 200, bonds: 1)
Molecule.create(atom1: "O", atom2: "Br", energy: 210, bonds: 1)
Molecule.create(atom1: "O", atom2: "I", energy: 220, bonds: 1)
Molecule.create(atom1: "O", atom2: "N", energy: 200, bonds: 1)
Molecule.create(atom1: "O", atom2: "O", energy: 180, bonds: 1)
Molecule.create(atom1: "O", atom2: "S", energy: nil, bonds: 1)

Molecule.create(atom1: "F", atom2: "F", energy: 159, bonds: 1)
Molecule.create(atom1: "Cl", atom2: "Cl", energy: 243, bonds: 1)
Molecule.create(atom1: "Br", atom2: "Br", energy: 193, bonds: 1)
Molecule.create(atom1: "I", atom2: "I", energy: 151, bonds: 1)
Molecule.create(atom1: "S", atom2: "F", energy: 310, bonds: 1)
Molecule.create(atom1: "S", atom2: "Cl", energy: 250, bonds: 1)
Molecule.create(atom1: "S", atom2: "Br", energy: 210, bonds: 1)
Molecule.create(atom1: "S", atom2: "S", energy: 225, bonds: 1)

Molecule.create(atom1: "C", atom2: "C", energy: 611, bonds: 2)
Molecule.create(atom1: "C", atom2: "C", energy: 835, bonds: 3)
Molecule.create(atom1: "C", atom2: "O", energy: 732, bonds: 2)
Molecule.create(atom1: "O", atom2: "O", energy: 498, bonds: 2)
Molecule.create(atom1: "N", atom2: "N", energy: 945, bonds: 3)


Element.create(name: "Hydrogen", symbol: "H", atomic_number: 1)
Element.create(name: "Carbon", symbol: "C", atomic_number: 6)
Element.create(name: "Nitrogen", symbol: "N", atomic_number: 7)
Element.create(name: "Oxygen", symbol: "O", atomic_number: 8)
Element.create(name: "Fluorine", symbol: "F", atomic_number: 9)
Element.create(name: "Sulfur", symbol: "S", atomic_number: 16)
Element.create(name: "Chlorine", symbol: "Cl", atomic_number: 17)
Element.create(name: "Bromine", symbol: "Br", atomic_number: 35)
Element.create(name: "Iodine", symbol: "I", atomic_number: 53)
